
version: "3"

networks:
  pubel:

volumes:
  prometheus_data:
services:
  exporter:
    build: 
      dockerfile: dockerfile
    container_name: my-exporter
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - pubel 
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=1d'
    ports:
      - "9090:9090"
    networks:
      - pubel 