global:
  scrape_interval: 10s 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "my-exporter"
    metrics_path: "/"
    static_configs:
      - targets: ["my-exporter:8000"]
